import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useCountry } from '@/utils/location'
import { Box, Flex, Heading, Text, VStack } from '@chakra-ui/react'
import ChakraSpinner from '@/components/Spinner'
import { useCarbonIntensityForecast } from '@/utils/electricityMaps'
import error from 'next/error'
import BadTime from '@/components/BadTime'
import GoodTime from '@/components/GoodTime'

const inter = Inter({ subsets: ['latin'] })
const CARBON_INTENSITY_THRESHOLD = 200

export default function Home() {
  const { data: country, error, isLoading } = useCountry()

  console.log(country, error, isLoading)

  const {
    data: carbonIntensity,
    error: carbonIntensityError,
    isLoading: carbonIntensityIsLoading,
  } = useCarbonIntensityForecast(country)

  console.log({
    carbonIntensity,
    carbonIntensityError,
    carbonIntensityIsLoading,
  })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        {carbonIntensity === undefined || carbonIntensityIsLoading ? (
          <Flex align={'center'} justify={'center'} minH={50} minW={50}>
            <ChakraSpinner />
          </Flex>
        ) : carbonIntensityError ? (
          <p>{String(carbonIntensityError)}</p>
        ) : (
          <>
            <Flex h={'60vh'} align='center' justify='center'>
              <VStack pt={50}>
                <Text>It is a</Text>
                {carbonIntensity > CARBON_INTENSITY_THRESHOLD ? (
                  <BadTime />
                ) : (
                  <GoodTime />
                )}
                <Text>to use electrical devices in your location.</Text>
              </VStack>
            </Flex>
          </>
        )}

        <VStack>
          <Text fontSize={'x-small'}>
            The current carbon intensity for {country} is {carbonIntensity}
          </Text>
          <a
            href='https://www.electricitymaps.com/'
            className={styles.card}
            target='_blank'
            rel='noopener noreferrer'
          >
            <p className={inter.className}>Powered by ⚡ Electricity Maps</p>
            <h2 className={inter.className}>
              Learn More <span>-&gt;</span>
            </h2>
          </a>

          {/* <a
            href='https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className={styles.card}
            target='_blank'
            rel='noopener noreferrer'
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href='https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className={styles.card}
            target='_blank'
            rel='noopener noreferrer'
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className={styles.card}
            target='_blank'
            rel='noopener noreferrer'
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a> */}
        </VStack>
      </main>
    </>
  )
}
